config/routes.rb
Rails.application.routes.draw do
  #when we receive a get request with URL `/about` then rails will invoke the
  #about controller with index action (action is just a method that is defined
  #within a controller)
  get '/about', to:'about#index'
  # if you don't pass an `as:` option then Rails will attempt to generate a URL
  # / PATH helper for you. If you pass the `as:` option then Rails will use
  # that as the URL/PATH helper. The auto-generated path helper will be
  # `contact_us_path` while after we added the `as:` option, it will just be
  # `contact_path`

  resources :questions
  # get('/contact_us', { to: 'contact#new', as: 'contact' })
  # post('/contact',{to:'contact#create',as:'contact_submit'})
  # get('/questions/new',{to:'questions#new', as:'new_question'})
  # post('/questions', {to:'questions#create', as:'questions'})
  # #the order of URLs matters because rails gives higher priority to routes that
  # #appear first
  # get('/questions/:id', {to:'questions#show', as:'question'})
  # #we don't need to put as option in here because we used the same url for the
  # #create action. Indeed rails will throw an error if you try to reuse a
  # #predefined path helper. Remember that the `as:` option defines a path/url
  # #helper which only generates a URL and isn't concerned about the VERB
  # get('/questions', { to:'questions#index'})
  # patch('/questions/:id', {to: 'questions#update'})
  # get('/questions/:id/edit', {to: 'questions#edit', as: 'edit_question'})
  # delete('/questions/:id', {to: 'questions#destroy'})
  root 'welcome#index'

  #you can also write it as:
  # get('/about' => 'about#index')

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  #http://guides.rubyonrails.org/association_basics.html#detailed-association-reference
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
#this is our Question model. it inherits from `ApplicationRecord` which inherits
#from `activerecord::base` which is a class that comes from rails
#all the functionalities we're going to be using in our question model come
#from `activerecord::base` which leverages ruby'ys meta programming features
class Question < ApplicationRecord
  has_many :answers

  # has_many :answers adds the following instance methods
  # to this model, Question:
  # answers
  # answers<<(object, ...)
  # answers.delete(object, ...)
  # answers.destroy(object, ...)
  # answers=(objects)
  # answers
  # answers=(ids)
  # answers.clear
  # answers.empty?
  # answers.size
  # answers.find(...)
  # answers.where(...)
  # answers.exists?(...)
  # answers.build(attributes = {}, ...)
  # answers.create(attributes = {})
  # answers.create!(attributes = {})
  # http://guides.rubyonrails.org/association_basics.html#has-many-association-reference


  # validates(:title, { presence: true, uniqueness: true })
  validates(:title, { presence: { message: 'must be present!' },
                      uniqueness: true,
                      exclusion: { in: %w(Apple Microsoft Sony) } })
  validates(:body,{ presence: true, length: { minimum: 5 } })
  validates :view_count, presence: true

  #this is used for custom-validation method, we expect to have a method called
  #`no_monkey` defined, ideally in the private section of the class
  validate :no_monkey

  after_initialize :set_defaults
  before_validation :titleize_title


  # scope :recent_five, lambda { order(created:at: :desc).limit(5) }

  def self.recent_five
    order(created_at: :desc).limit(5)
  end

  private

  def titleize_title
    self.title = title.titleize if title.present?
  end

  def set_defaults
    self.view_count ||= 0
  end

  def no_monkey
    if title.present? && title.downcase.include?('monkey')
      #this will make the record invalid, even if there is error on the record
      #by using errors.add then the record won't save because it won't be valid
      errors.add(:title, 'can\'t include monkey!')
    end
  end

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    #you can do something like this: (assuming about folder is in views folder)
    # render 'about/index'

    #you can also do:
    # render :index
    #the above will assume that `index` template is inside `about` folder
    #because we're inside the `AboutController`

    #if you put nothing, then Rails will default to rendering:
    # app/views/about/index.html.erb because we're inside the AboutController
    # and `index` action (method) in that controller.

    #note convention in naming Rails template
    # ACTION.FORMAT.TEMPLATING_SYSTEM
    # FORMAT: default to `html` unless you specify otherwise
    #         if you go to localhost:3000/about.text then the format will be
    #         `text` (provided view index.text.erb exists)
    # TEMPLATING_SYSTEM: default to ERB unless you install another gem for an
    # =>                 an alternate templating system. available ones include
    # =>                 HAML and SLIM
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def new
  end
  def create
    #if you want to define a variable that you can access in the view file then
    #you will need to define the variable as an instance variable as in:
    @name = params[:name] # you can access this inside the view file
                          # such as: create.html.erb

    #this will render a plain text response that has a body of 'Thank you for
    #contacting us'
    render plain: "Thank you #{params[:name]} for contacting us"
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :find_question, only: [:show, :edit, :update, :destroy]
  def new
    #we instantiate a new `question` object because it will help us in generating
    #the form in `views/new.html.erb`. We have to make it an instance variable
    #so we can access it in the view file
    @question = Question.new
  end
  def create
    #the line below is what's called Strong Parameters feature that was added
    #to rails starting with version 4 to help developers be more explicit about
    #the parameters that they want to allow the user to submit

    question_params = params.require(:question).permit([:title,:body])
    question = Question.new question_params
    # Rails.logger.info '>>>>>>>>>>>>>>'
    # Rails.logger.info question.errors.full_messages
    # Rails.logger.info '>>>>>>>>>>>>>>'
    @question = Question.new question_params
    if @question.save
      # render plain: 'question created successfully'

      # rails gives us access to `flash` object which looks like a Hash. flash
      # utilizes cookies to store a bit of information that we can access in the
      # next request. Flash will automatically be deleted when it's displayed.
      flash[:notice] = "question created!"
      redirect_to question_path(@question)
    else
      flash.now[:alert] = 'Please fix errors below'
      render :new
      # render plain: "errors: #{question.errors.full_messages.join(', ')}"
    end
  end

  def show
  end

  def index
    @question = Question.last(50)
  end

  def edit
  end

  def update
    @question = Question.find params[:id]
    question_params = params.require(:question).permit([:title, :body])
    if @question.update(question_params)
      redirect_to question_path(@question)
    else
      render :edit
    end
  end
  def destroy
    question.destroy
    redirect_to questions_path

  end
  def find_question
    @question = Question.find params[:id]
  end

  def question_params
    # the line below is what's called "Strong Parameters" feautre that was added
    # to Rails starting with version 4 to help developer be more explicit about
    # the parameters that they want to allow the user to submit
    params.require(:question).permit([:title, :body])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.erb
<h1>about us</h1>

app/views/contact/new.html.erb
<h1>Contact us</h1>

<!-- form_tag is a rails bult-in helper to generate a form, the first argument
      of the form_tag must be the URL that the form will submit to. Generated
      form will have POST as their method and they will automatically generate
      auth token-->
<%= form_tag contact_submit_path do%>
  <%# will generate a submit button for the form with label 'Contact Us' %>
  <div class="">
    <%= label_tag :name %>
    <%= text_field_tag :name %>
  </div>
  <div class="">
    <%= label_tag :email %>
    <%= email_field_tag :email %>
  </div>
  <div class="">
    <%= label_tag :message %>
    <%= text_area_tag :message %>
  </div>
  <%= submit_tag 'Contact Us' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AwesomeAnswers</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <!-- <a href="/"> Home </a>-->
    <!-- link_to is a built in Rails helper that generates an `<a>`tag. the
         first arg is the anchor text and the second arg is the URL or path.
         It's best to use Rails generated path/url helpers -->
    <%= link_to 'Home', root_path %>
    |
    <%= link_to 'About Us', about_path %>
    |
    <%= link_to 'All Questions', questions_path %>
    <hr>
      <% if flash[:notice] %>
        <div class="flash-success"><%= flash[:notice] %></div>
        <hr>
      <% elsif flash[:alert] %>
        <div class="flash-alert"><%= flash[:alert] %></div>
        <hr>
      <% end %>

    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= @question.errors.full_messages.join(', ') %>

<%= form_for @question do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <%= f.submit %>
<% end %>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>


<%# if you pass a persisted ActiveRecord object to the `form_For`, then form_for
    will submit a PATCH request instead of POST using a hidden_field technique
    and the URL for the form will be in this case the `update` action URL. in
    our case this is question_path(@question) %>

<%= render 'form' %>

app/views/questions/index.html.erb
<h1>All questions</h1>

<% @question.each do |question| %>
  <h3><%= link_to question.title, question_path(question) %></h3>
  <hr>
<% end %>

app/views/questions/new.html.erb
<h1>New Question</h1>
<%# form_for is a built-in rails helper that enables us to generate a form from
    an activerecord model to submit to the associated controller. if you pass in
    a non-persisted ActiveRecord object (not in the dB yet) then `form_for` will
    automatically assume that this form will submit to the `create` action in
    the associated controller ( in our case questions#create ) which has a PATH
    helper of `questions_path` so we must have `questions_path` defined

    %>

<%# render helps you insert a partial. Rails expects in here that you defined
    a partial within the same folder of this file (new.html.erb) called
    _form.html.erb . Note that partials will have access to instance variables
    so there is no need to pass them explicitly. If you want to pass a local
    variable, then you'll need to do so explicitly... as in
      render 'form, my_var: 'abc'
    Also, if the partial is in another folder (such as contact) then you will
    have to put the full path for the partial as in:
      render '/contact/form'
    %>
<%= render 'form' %>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>
<p><%= @question.body %></p>

<%#rails enables us to make links and non-GET requests by setting the `method`
    attribute for `link_to`. Rails uses Javascript to accomplish that. %>
<h3><%= link_to 'edit', edit_question_path(@question)%></h3>
<h3><%= link_to 'delete', question_path(@question), method: :delete, data: {confirm:'Are you sure?'} %></h3>

app/views/welcome/index.html.erb
<h1>Awesome Answers</h1>

<%= link_to 'New Question', new_question_path %>